name: dsbroker
version: 1.0.0
description: DSA Broker
dependencies:
  uuid: 1.0.1
  dslink:
    git:
      url: https://github.com/IOT-DSA/sdk-dslink-dart.git
      ref: feature/156805-StrictTLSCerts
environment:
  sdk: ^1.11.0
executables:
  dsbroker: broker
