name: dsbroker
version: 1.0.0
description: DSA Broker
dependencies:
  dslink:
    git: 
      url: https://github.com/IOT-DSA/sdk-dslink-dart.git
      ref: debug/attribute-logging
environment:
  sdk: ^1.11.0
executables:
  dsbroker: broker
